server:
  port: 9000
  servlet:
    context-path:/demo  
   

spring:
  datasource:
    username: jrtp
    password: Jrtp21@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/report_api
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
        
    
       
